current_exchanger/api/urls.py
from django.urls import path,include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

from . import views
app_name = 'api'

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    
    path('currency/exchange/', views.CurrencyExchange.as_view(), name='currency_exchange'),
]

current_exchanger/currency/urls.py
from django.urls import path
from . import views
app_name = 'currency'

urlpatterns = [
    path('currency/table/', views.table, name='table'),
    path('currency/changer/', views.changer, name='changer'),
    
    path('auth/login/', views.UserLogin, name='login'),
    path('auth/register/', views.UserRegister, name='register'),
    path('auth/logout/', views.UserLogout, name='logout'),
]

current_exchanger/current_exchanger/urls.py
from django.contrib import admin
from django.urls import path, include
from currency import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('currency.urls')),
    path('', views.table, name='table'),
]

current_exchanger/api/models.py
from django.db import models

# Create your models here.

current_exchanger/currency/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError

def validate_positive(value):
    if value <= 0:
        raise ValidationError(_('%s(value) must be positive'), params={"value": value})
    
# Create your models here.
class Currency(models.Model):
    UID = models.CharField('UID', max_length=10, null=False, unique=True)
    NumCode = models.CharField('NumCode', max_length=3, unique=True)
    CharCode = models.CharField('CharCode', max_length=3, unique=True)
    Nominal = models.IntegerField('Nominal', validators=[MinValueValidator(1)])
    Name = models.CharField('Name', max_length=50)
    Value = models.FloatField('Value', validators=[validate_positive])
    Previous = models.FloatField('Previous', validators=[validate_positive])
    
    def __str__(self):
        return self.CharCode
    
    def exchange_to(self, ammount:int, currency):
        if type(currency) != type(self):
            raise TypeError('currency must be of type Currency')
        return ammount * self.Value / self.Nominal / currency.Value * currency.Nominal
    

current_exchanger/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from currency.models import Currency
from .serializers import CurrencySerializer
from rest_framework import status
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework.permissions import IsAuthenticated

class CurrencyExchange(APIView):
    permission_classes=[IsAuthenticated]
    authentication_classes=[JWTAuthentication]
    def get(self, request):
        currencies = Currency.objects.all()
        serializer = CurrencySerializer(currencies, many=True)
        if serializer.data:
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def post(self, request):
        currencyFrom = request.data['currencyFrom']
        currencyTo = request.data['currencyTo']
        ammount = request.data['ammount']
        try:
            ammount = float(ammount)
        except:
            return Response("Invalid data", status=status.HTTP_400_BAD_REQUEST)
        if ammount <= 0:
            return Response("Amount should be more than zero", status=status.HTTP_400_BAD_REQUEST)
        if not(Currency.objects.filter(CharCode=currencyFrom).exists() and Currency.objects.filter(CharCode=currencyTo).exists() and (type(ammount) in [int, float])):
            return Response("Invalid data2", status=status.HTTP_400_BAD_REQUEST)
        currencyFrom = Currency.objects.filter(CharCode=currencyFrom).first()
        currencyTo = Currency.objects.filter(CharCode=currencyTo).first()
        result = currencyFrom.exchange_to(ammount, currencyTo)
        return Response(f"{result}", status=status.HTTP_200_OK)
# {
#     "currencyFrom": "USD",
#     "currencyTo": "RUB",
#     "ammount": 1
# }

current_exchanger/currency/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.conf import settings
from currency.models import Currency


def upd_cur():
    try:
        for i in settings.AVAILABLE_CURRENCIES:
            # Проверяем, существует ли запись с таким UID
            currency = Currency.objects.filter(UID=i['UID']).first()
            if currency:
                # Если запись существует, обновляем её
                for key, value in i.items():
                    setattr(currency, key, value)
                currency.save()
            else:
                # Если записи нет, создаём новую
                Currency.objects.create(**i)
    except Exception as e:
        print(e)
        pass


upd_cur()
    

def UserLogin(request):
    context = {
        'title': 'Login',
        'pageTitle': 'Login',
        'btn': 'Login'
    }
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('currency:table')
        else:
            context['err'] = 'Invalid Username or Password'
            return render(request, 'logauth/login.html', context)
    return render(request, 'logauth/login.html', context)

def UserLogout(request):
    logout(request)
    return redirect('currency:login')

def UserRegister(request):
    context = {
        'title': 'Register',
        'pageTitle': 'Register',
        'btn': 'Create'
    }
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if User.objects.filter(username=username).exists():
            context['err'] = 'Username already exists'
            return render(request, 'logauth/login.html', context)
        else:
            user = User.objects.create_user(username=username, password=password)
            login(request, user)
            return redirect('currency:table')
    else:
        return render(request, 'logauth/login.html', context)

def table(request):
    upd_cur()
    if not (request.user.is_authenticated):
        return redirect('currency:login')

    context = {
        'pageTitle': 'Currency Exchange Table',
        'currencies': Currency.objects.all(),
    }
    return render(request, 'currency/table.html', context)


def changer(request):
    if not (request.user.is_authenticated):
        return redirect('currency:login')

    context = {
        'pageTitle': 'Currency Exchange',
        'currencies': Currency.objects.all(),
        'Val': {i.CharCode: {"Value": i.Value, "Nominal": i.Nominal} for i in Currency.objects.all()}
    }
    return render(request, 'currency/changer.html', context)

current_exchanger/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{pageTitle}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
        textarea {
            resize: none;
        }
        .form-wrapper > div {
            display: inline-block;
            margin: 10px 10px;
        }

        .form-wrapper > div > input {
            max-width: 100px;
        }
    </style>
</head>
<body>
    {%if error %}
        <script>alert("{{error}}")</script>
    {%endif%}
    {%if success %}
        <script>alert("{{success}}")</script>
    {%endif%}
    {% block content %}
    {% endblock content %}
</body>
</html>

current_exchanger/templates/currency/changer.html
{% extends "base.html" %}
{% block content %}
{% if request.user.is_authenticated %}
<style>
    /* Общий стиль */
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f6f9;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .form-wrapper {
        background: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        text-align: center;
        width: 400px;
    }

    .form-wrapper div {
        margin: 15px 0;
    }

    input[type="text"], input[type="number"] {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ddd;
        border-radius: 5px;
        font-size: 16px;
    }

    input[type="text"]::placeholder, input[type="number"]::placeholder {
        color: #aaa;
    }

    .alert {
        background-color: #f0f0f0;
        color: #333;
        padding: 10px;
        border-radius: 5px;
        position: fixed;
        top: 10px;
        right: 10px;
        max-width: 200px;
        text-align: center;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .logout-button {
        display: inline-block;
        padding: 10px 15px;
        background-color: #ff4d4f;
        color: white;
        text-decoration: none;
        border-radius: 50px;
        font-weight: bold;
        font-size: 14px;
        border: none;
        transition: all 0.3s ease;
        cursor: pointer;
    }

    .logout-button:hover {
        background-color: #d9363e;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
        transform: scale(1.05);
    }

    h1 {
        font-size: 24px;
        margin-bottom: 20px;
        color: #333;
    }
</style>


<div class="alert">
    {{request.user.username}}<br>
    <a href="{% url 'currency:logout' %}" class="logout-button">Logout</a>
</div>

<div class="form-wrapper">
    <h1>Currency Converter</h1>
    <div>
        <datalist id="id_From">
            {% for currency in currencies %}
            <option value="{{currency.CharCode}}">{{currency.CharCode}}</option>
            {% endfor %}
        </datalist>
        <input class="from" type="text" id="id_From" list="id_From" placeholder="From">
    </div>
    <div>
        <datalist id="id_To">
            {% for currency in currencies %}
            <option value="{{currency.CharCode}}">{{currency.CharCode}}</option>
            {% endfor %}
        </datalist>
        <input class="to" type="text" id="id_To" list="id_To" placeholder="To">
    </div>
    <div>
        <input class="amount" type="number" id="id_Amount" placeholder="Amount">
    </div>
    <div>
        <input class="total" type="number" id="id_Total" placeholder="Total">
    </div>
</div>
{% endif %}
<script>
    let To = document.getElementsByClassName('to')[0];
    let From = document.getElementsByClassName('from')[0];
    let Result = document.getElementsByClassName('total')[0];
    let Amount = document.getElementsByClassName('amount')[0];
    let Val = {{Val|safe}}
    To.addEventListener('change', function () {
        Result.value = Val[From.value]['Value'] * Amount.value * Val[To.value]['Nominal'] / Val[To.value]['Value'] / Val[From.value]['Nominal'];
    })

    From.addEventListener('change', function () {
        Result.value = Val[From.value]['Value'] * Amount.value * Val[To.value]['Nominal'] / Val[To.value]['Value'] / Val[From.value]['Nominal'];
    })
    Amount.addEventListener('change', function () {
        if(Amount.value >= 0){
            Result.value = Val[From.value]['Value'] * Amount.value * Val[To.value]['Nominal'] / Val[To.value]['Value'] / Val[From.value]['Nominal'];
        } else{
            Amount.setCustomValidity('Поддерживается ввод только неотрицательных чисел');
            Amount.reportValidity();
        }
    })
    Result.addEventListener('change', function () {
        if(Result.value >= 0){
            Amount.value = Result.value / (Val[From.value]['Value'] * Val[To.value]['Nominal'] / Val[To.value]['Value'] / Val[From.value]['Nominal'])
        } else {
            Result.setCustomValidity('Поддерживается ввод только неотрицательных чисел');
            Result.reportValidity();
        }
    })
</script>
{% endblock content %}

current_exchanger/templates/currency/table.html
{% extends "base.html" %}
{% block content %}
{% if request.user.is_authenticated %}
<style>
    /* Общий стиль */
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f6f9;
        margin: 0;
        padding: 0;
    }

    .alert {
        background-color: #f0f0f0;
        color: #333;
        padding: 10px;
        border-radius: 5px;
        position: fixed;
        top: 10px;
        right: 10px;
        max-width: 200px;
        text-align: center;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .logout-button {
        display: inline-block;
        padding: 10px 15px;
        background-color: #ff4d4f;
        color: white;
        text-decoration: none;
        border-radius: 50px;
        font-weight: bold;
        font-size: 14px;
        border: none;
        transition: all 0.3s ease;
        cursor: pointer;
    }

    .logout-button:hover {
        background-color: #d9363e;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
        transform: scale(1.05);
    }

    .container {
        background: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin: 50px auto;
        max-width: 900px;
    }

    h1 {
        font-size: 28px;
        margin-bottom: 20px;
        color: #333;
        text-align: center;
    }

    hr {
        border: none;
        border-top: 2px solid #ddd;
        margin: 10px 0;
    }

    .table {
        width: 100%;
        margin-top: 20px;
        border-collapse: collapse;
    }

    .table th, .table td {
        padding: 12px 15px;
        border: 1px solid #ddd;
        text-align: center;
        color: #555;
    }

    .table th {
        background-color: #f8f9fa;
        font-weight: bold;
        font-size: 16px;
    }

    .table tr:nth-child(even) {
        background-color: #f4f6f9;
    }

    .table tr:hover {
        background-color: #e9ecef;
    }
</style>


<div class="alert">
    {{request.user.username}}<br>
    <a href="{% url 'currency:logout' %}" class="logout-button">Logout</a>
</div>


{% endif %}
<div class="container">
    <h1 class="text-center" style="padding-top: 2em;">Current Exchanger</h1>
    <hr style="weight: 1px; color: #000000;">
    <table class="table table-bordered text-center">
        <tr>
            <th>UID</th>
            <th>NumCode</th>
            <th>CharCode</th>
            <th>Nominal</th>
            <th>Name</th>
            <th>Value</th>
            <th>Previous</th>
        </tr>
        {%for currency in currencies%}
        {%if currency.CharCode != 'RUB'%}
        <tr>
            <td>{{currency.UID}}</td>
            <td>{{currency.NumCode}}</td>
            <td>{{currency.CharCode}}</td>
            <td>{{currency.Nominal}}</td>
            <td>{{currency.Name}}</td>
            <td>{{currency.Value}}</td>
            <td>{{currency.Previous}}</td>
        </tr>
        {%endif%}
        {% endfor %}
    </table>
</div>
{% endblock content %}

current_exchanger/templates/logauth/login.html
{% extends 'base.html' %}
{% block content %}
<style>
    /* Общий стиль */
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f6f9;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .container {
        background: #ffffff;
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        width: 400px;
        text-align: center;
    }

    h2 {
        font-size: 24px;
        margin-bottom: 20px;
        color: #333;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ddd;
        border-radius: 5px;
        font-size: 16px;
    }

    .form-control::placeholder {
        color: #aaa;
    }

    .btn-primary {
        display: block;
        width: 100%;
        padding: 10px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }

    a {
        display: block;
        margin-top: 10px;
        color: #007bff;
        text-decoration: none;
        font-size: 14px;
    }

    a:hover {
        text-decoration: underline;
    }

    .alert-danger {
        padding: 10px;
        border-radius: 5px;
        background-color: #ff4d4f;
        color: #fff;
        font-weight: bold;
        margin-bottom: 20px;
    }
</style>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h2 class="text-center" style="margin-bottom: 50px">{{title}}</h2>
                {% if err %}
                <div class="alert alert-danger text-center" role="alert"> <h2> {{err}}</h2></div> 
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" name="username" placeholder="Пользователь" class="form-control mb-2">
                    <input type="password" name="password" placeholder="Пароль" class="form-control mb-2">
                    <button type="submit" class="btn btn-primary">{{btn}}</button>
                    
                    {% if title == 'Login' %}<a href="{% url 'currency:register'%}">Register</a> 
                    {% else %}<a href="{% url 'currency:login'%}">Login</a>
                    {%endif%}
                </form>
            </div>
        </div>
    </div>
{% endblock content %}